language: node_js
node_js:
- lts/*
before_install:
- npm install -g @angular/cli
install:
- npm install

branches:
  only:
  - main
deploy:
  provider: heroku
  api_key:
    secure: dd34f4bc-2e81-4e06-b866-9f6e7d876fa8
  app: steam-clone